markdown: kramdown
highlighter: rouge
#permalink: blog/:year/:month/:day/:title.html
permalink: :title.html
paginate: 6	
paginate_path: page/:num


# Build settings
# markdown: redcarpet
# redcarpet:
#     extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]

#SyntaxHihglighter config start

SyntaxHihglighter: false
shTheme: shThemeDefault # shThemeDefault  shThemeDjango  shThemeEclipse  shThemeEmacs  shThemeFadeToGrey  shThemeMidnight  shThemeRDark

#SyntaxHihglighter config end

#使用前阅读↓↓↓↓↓↓↓↓↓
#感谢您克隆此模板,但在使用前麻烦请把"<---"标记的更换成您的信息或删除(值留空白即可).非常感谢.
#使用前阅读↑↑↑↑↑↑↑↑↑
blog:
    name: arrfu                                          # 博客名称
    description: Keep Moving                             # 博客描述
    title: arrfu                                         # 网页标题
    url: http://arrfu.github.io/                         # 博客地址
    duoshuo: arrfu                                       # 多说ID       <---
    tongji: 25bfa0f4ae7254dd69d9017efa436ed2                                             # 百度统计ID   <--- 
    clickiTongJi: 					                     # Clicki统计ID <---
    qiniu:                                               # 七牛云地址
   
author:
    name: arrfu                                          # 作者名称
    email: root@arrfu.com                                # 邮箱地址
    weibo: http://weibo.com/u/2104089844                            # 微博地址
    github: https://github.com/arrfu                     # GitHub地址
    logo: /res/img/icon.jpg                              # logo地址
    douban:
        name: arrfu                                           # 豆瓣地址名称
        key:                                             # 豆瓣API Key
    
